on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build typescript
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: |
        cd server
        npm install -g yarn && yarn && yarn build

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "./server"
        target: ${{ secrets.SERVER_PATH }}

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd ${{ secrets.SERVER_PATH }}/server
          SECRET_KEY=${{ secrets.SECRET_KEY }} NODE_ENV=production pm2 restart main --update-env
